### ISSUE TITLE
Investigate use of content components as documentation includes

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern.github.io#131]
Bloke had brought up [the idea](https://forum.textpattern.com/viewtopic.php?pid=320129#p320129) in the forum of using content components (pieces of text, usually at paragraph level, focused on single topics) as a tool in docs development. I think it's a great idea if done strategically (and not overused) for trivial types of information that nevertheless often needs repeated in multiple places. I don't know what the best way is to handle this in this platform, but let's give it some research and thought.

(I'm not taking this on, as GitHub tech is not my forte, but I'm happy to follow along with discussing the _what_ and _where_ as it concerns content.)

**Comment by Bloke** [comment]
Jekyll itself [supports includes](https://jekyllrb.com/docs/includes/) so if we can stuff common things in an `_includes` directory tat keeps everything compartmentalized and is easy to see if we have a component already written.

Things like "Logging in to Textpattern" might benefit with being here. And I think listing all the prefs separately with a suitable naming convention to lump them together (e.g. `pref_comments_on-by-default.md`, `pref_site_url.md` etc).

That also (perhaps) gives us the option to programmatically include them in the doc describing the Preferences panel itself, instead of including them all by hand. If we can grab all the `pref_*` files and then split the names up on the next underscore (which indicates the group in which they reside) followed by the `name-of-the-pref.md` we can pretty much build the page with a few lines of code, as well as having every pref available as a separate topic if we ever need to "include" them in another doc.

The million dollar question is whether GitHub's implementation of Jekyll supports includes and looping over filenames or not. Anyone know?

**Comment by philwareham** [comment]
Yes GitHub Pages supports includes - we already have that directory with some global bits and pieces in it https://github.com/textpattern/textpattern.github.io/tree/master/_includes

I'm not sure what you mean by looping over filenames, specifically. Sorry.

**Comment by Bloke** [comment]
Cool, thanks. The looping include thing might not be necessary after [further discussion](https://github.com/textpattern/textpattern.github.io/issues/132) as we might just create a directory of 'common stuff' and link to them instead of include them.

**Comment by philwareham** [comment]
You can simply add liquid tags in your Markdown articles like so...

    {% include my-great-component.html %}

..which outputs the corresponding file with the `_includes` directory within your article.

I think that those includes have to be standard HTML though, I don't think you can include another Markdown fragment within a Markdown file (although I've not tested that theory). You could maybe try a test:

    {% include my-great-component.md %}

**Comment by wion** [comment]
@Bloke, are we past the exploration on this. Can it be closed? If so, go ahead.

**Comment by Bloke** [comment]
Yes, it works... mostly. Hoping when we move to self-hosted that some of the other things (such as search fragments) will work and not be nobbled by GitHub's limited implementation.

**Comment by wion** [comment]
Okay, thanks. I vaguely recall there were some github constraints. I think with redirecting changed URLs, too, iirc.
