### ISSUE TITLE
breadcrumbs should be generated by Jekyll

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern.github.io#31]
Some of the docs pages have breadcrumbs manually coded in them. This can and should be done via Jekyll's templates instead.

I will add the code in due course. Docs will need any manually breadcrumbs deleted from them.

**Comment by wion** [comment]
Good. I was going to ask about that anyway. There's not many yet, because the editing is going slowly. I just wanted to demonstrate the idea. Hopefully Jekyll does it in a half-humane manner.

**Comment by philwareham** [comment]
It's an extension I think - I'll investigate.

**Comment by philwareham** [comment]
For my reference: http://blog.comsysto.com/2015/04/25/automatic-breadcrumb-for-jekyll-on-github-pages/

**Comment by wion** [comment]
I'm not sure I really understand the liquid statement part, but if I understand the actual breadcrumb code part then this might work for you. It changes the "Home" link to "ToC" which would be better, IMO, because people might think of "Home" as the .com homepage. And it changes all  instances of "_index.html" to "_index.textile". I don't know if that's necessary, but it seemed to me like it would be in this case.

bc. <ol class="breadcrumb">
<li><a href="{{ site.baseurl }}/">ToC</a></li>
{% capture page_url_without_index_textile %}{{ page.url | remove: "/index.textile" }}{% endcapture %}
{% assign splitted_url_parts = page_url_without_index_textile | split: '/' %}
{% capture forLoopMaxInt %}{{ splitted_url_parts.size | minus:1 }}{% endcapture %}
{% for i in (1..forLoopMaxInt) %}
    {% capture current_breadcrumb_url %}{{next_prepender}}/{{ splitted_url_parts[i] }}/index.textile{% endcapture %}
    {% capture current_breadcrumb_md_url %}{{next_prepender}}/{{ splitted_url_parts[i] }}/{% endcapture %}
    {% capture next_prepender %}{{next_prepender}}/{{ splitted_url_parts[i] }}{% endcapture %}
    {% for breadcrumb_page in site.pages %}
        {% if current_breadcrumb_url == breadcrumb_page.url or current_breadcrumb_md_url == breadcrumb_page.url  %}
            <li {% if i == forLoopMaxInt %}class="active"{% endif %}>
                {% capture breadcrumb_page_page_url_without_index_textile %}{{ breadcrumb_page.url | remove: "index.textile" }}{% endcapture %}
                <a href="{{ site.baseurl }}{{breadcrumb_page_page_url_without_index_textile}}">{{breadcrumb_page.breadcrumb}}</a>            </li>
        {% endif %}
    {% endfor %}
{% endfor %}
</ol>

I still don't know how these will look. The guy's demo page doesn't really demo anything as far as I can tell, so it remains to be tested, I guess.

**Comment by wion** [comment]
With regard to issue #40 ...

We do need some kind of intra-site navigation aide, like the breadcrumb provides, but if that particular script doesn't work in an ideal manner, then maybe we need to scrap that for a better approach, even if an alternative approach is not as all-in-one as the script is. 

For example, WikiMedia allowed for creating "templates, which were essentially partials of content that you could insert anywhere with a single tag like this, {{template-name}}. This is how we created the intra-navigation lists there. I assume Jekyll has similar functionality (inserts) if not the same kind of tag system. 

So instead of a single script thing that imposes constraints on intra-nav design, we have a series of inserts for breadcrumbs. We'll need more than one, of course, but we can be as economic as possible. 

Take the /administration branch as an example, and the Diagnostics panel as a sample target. We could write a breadcrumb insert called "admin-breadcrumbs" and put this in it:

`"ToC":../ > " Administration > "Admin":/admin/users-panel > `

That works for every page in the /admin folder. Then for every admin-side panel doc, we'd call the partial above the H1 header and slap on the active page name:

`{{admin-breadcrumbs}}Diagnostics panel`

Which would then create:

 > [ToC](http://docs.textpattern.io) > Administration > [Admin](http://docs.textpattern.io/administration/admin/users-panel) > Diagnostics panel

And because we're writing these ourselves, we can design the labels and links anyway we want. For example, if we think it's better to leave out "Administration", no big deal:

 > [ToC](http://docs.textpattern.io) > [Admin](http://docs.textpattern.io/administration/admin/users-panel) > Diagnostics panel

Or maybe we model it this way, where each piece is it's own partial, the partial paths exist for each sub-directory location, and assuming Jekyll is aware of what is an active page...

* {{toc}}  = `"ToC":../ > `
* {{admin-path}}  = `Administration >  `
* {{active-page}}  = `Diagnostics panel`(auto-identified)

Then we'd just put the relevant pieces together above the H1 as before:

`{{toc}}{{admin-path}}{{active-page}}`

Something like that. It's basically the same idea as working with Txp tags (and forms). It takes a little time to set up the templates initially, but later it's easy to use. The only question is whether Jekyll allows us to do something like that and if it's aware of active pages. In the latter case we could simplify a template further by nesting the active template in the path:

`{{admin-path}}  = `Administration >  {{active-page}}`

And we'd only have to add this for all admin page:

`{{toc}}{{admin-path}}`

Likewise for all presentation pages:

`{{toc}}{{presentation-path}}`

And so on.

**Comment by philwareham** [comment]
Jekyll can't do breadcrumbs without a plugin (which you can't use on GitHub). Will design around this. Closing.
