### ISSUE TITLE
Tag reference PDF

### ISSUE THREAD

**Issue by vanmelick** [textpattern/textpattern.github.io#51]
The tag reference book PDF that is offered in the Wiki is no longer working (gives a zero byte file):
http://www.textpattern.net/wiki/index.php?title=Category:Tag_Reference

Reported in the forum:
http://forum.textpattern.com/viewtopic.php?id=39593
http://forum.textpattern.com/viewtopic.php?id=46609

**Comment by philwareham** [comment]
That is not directly related to this repo and I didn't intend on having a PDF version in the new site.

However, there is this Jekyll plugin that can create PDFs from Jekyll flat files. Unfortunately it is a plugin, and plugins are not permitted on GitHub's hosted Jekyll sites. So that limits whether we can use it (I could generate manually from a local hosted Jekyll site but it would not be dynamically generated then).

**Comment by vanmelick** [comment]
I didn't know where else to open an issue for this.

**Comment by philwareham** [comment]
No worries. The old site will be retired in January/February next year so I won't be doing any fixes or updates to that codebase. Closing for now.
